/* eslint-disable no-use-before-define */

import React from 'react';
import Checkbox from '@mui/material/Checkbox';
import TextField from '@mui/material/TextField';
import Autocomplete from '@mui/material/Autocomplete';
import CheckBoxOutlineBlankIcon from '@material-ui/icons/CheckBoxOutlineBlank';
import CheckBoxIcon from '@material-ui/icons/CheckBox';

const icon = <CheckBoxOutlineBlankIcon fontSize="small" />;
const checkedIcon = <CheckBoxIcon fontSize="small" />;

export default function CheckboxesTags() {
    return (
        <Autocomplete
            multiple
            id="checkboxes-tags-demo"
            options={itemsSousCategory}
            disableCloseOnSelect
            getOptionLabel={(option) => option.title}
            renderOption={(option, { selected }) => (
                <React.Fragment>
                    <Checkbox
                        icon={icon}
                        checkedIcon={checkedIcon}
                        style={{ marginRight: 8 }}
                        checked={selected}
                    />
                    {option.title}
                </React.Fragment>
            )}
            style={{ width: 500 }}
            renderInput={(params) => (
                <TextField {...params} variant="outlined" label="Checkboxes" placeholder="Favorites" />
            )}
        />
    );
}






export const itemsSousCategory = [
    { title: 'Agriculture' },
    { title: 'Agro-industrie' },
    { title: 'Alimentation animale' },
    { title: 'Boissons (fabrication, embouteillage)' },
    { title: 'Brasseries' },
    { title: "Café, Cacao (caisse de péréquation)" },
    { title: 'Café, Cacao (transformation)' },
    { title: 'Chocolaterie' },
    { title: 'Coton, Cotonnerie' },
    { title: 'Distilleries' },
    { title: 'Eaux minérales (production)' },
    { title: 'Engrais' },
    { title: 'Farine' },
    { title: 'Hévéaculture' },
    { title: 'Huile alimentaire, Huilerie' },
    { title: "Lait, Yaourt " },
    { title: 'Matériel agricole et forestier' },
    { title: 'Minoterie, meunerie' },
    { title: 'Produits laitiers' },
    { title: 'Savons, savonnerie Sucre (Industrie)' },
    { title: 'Agrégats (production et vente)' },
    { title: "Adduction d'eau" },
    { title: 'Assainissement' },
    { title: "Bâtiment (entreprises)" },
    { title: 'Carrelage, Sanitaires' },
    { title: 'Chaudronnerie' },
    { title: 'Ciment (Importation, distribution)' },
    { title: 'Cimenteries' },
    { title: 'Climatisation (entreprises)' },
    { title: 'Construction métallique' },
    { title: 'Décoration, Agencement' },
    { title: 'Dépollution' },
    { title: 'Electricité (entreprises)' },
    { title: 'Electricité (instrumentation)' },
    { title: 'Electricité (matériel et fournitures)' },
    { title: 'Electricité industrielle' },
    { title: 'Engins TP et chantier (location)' },
    { title: 'Engins TP et chantier (vente)' },
    { title: 'Entretien routier, VRD' },
    { title: 'Etanchéité, isolation' },
    { title: 'Forages, sondages' },
    { title: 'Froid Industriel' },
    { title: 'Génie Climatique' },
    { title: 'Hydraulique villageoise' },
    { title: 'Maintenance industrielle' },
    { title: 'Matériaux de construction (négoce)' },
    { title: 'Mécanique de précision' },
    { title: 'Mécanique générale' },
    { title: 'Meubles, mobilier (fabrication)' },
    { title: 'Nettoyage industriel' },
    { title: 'Pavés (fabrication et pose)' },
    { title: 'Pipeline' },
    { title: 'Plomberie (entreprises)' },
    { title: 'Produits métallurgiques' },
    { title: 'Profilés, fer à béton' },
    { title: 'Quincaillerie' },
    { title: 'Recyclage' },
    { title: 'Soudure industrielle' },
    { title: 'Terrassement' },
    { title: 'Traitement des déchets' },
    { title: 'Travaux maritimes et portuaires Travaux publics, Génie Civil' },
    { title: 'Alarme, matériel de sécurité' },
    { title: 'Auto-écoles' },
    { title: 'Automobiles (accessoires, pièces détachées)' },
    { title: 'Automobiles (concessionnaire)' },
    { title: 'Automobiles (contrôle technique)' },
    { title: 'Automobiles (expertise)' },
    { title: 'Automobiles (occasion)' },
    { title: 'Bijouteries-Joaillerie-Horlogerie' },
    { title: 'Boissons (importation, distribution)' },
    { title: 'Boulangerie, Patisserie' },
    { title: 'Bureautique' },
    { title: 'Café, Cacao (Commercialisation)' },
    { title: 'Café, Cacao (torréfaction, distribution)' },
    { title: 'Camions - Poids Lourds' },
    { title: "Centrales d'achat" },
    { title: 'Commerce général' },
    { title: 'Cosmétiques (fabrication, distribution)' },
    { title: 'Electroménager' },
    { title: 'Equipements de protection individuelle' },
    { title: 'Extincteurs' },
    { title: 'Garages' },
    { title: 'Géolocalisation, Tracking, Traçabilité' },
    { title: 'Groupes électrogènes' },
    { title: 'Hygiène (produits et distibuteurs)' },
    { title: 'Import-export' },
    { title: 'Location de voitures' },
    { title: "Matériel d'incendie" },
    { title: 'Matériel de levage' },
    { title: 'Matériel et équipements bancaires' },
    { title: 'Matériel et mobilier de bureau' },
    { title: 'Matériel industriel' },
    { title: 'Meubles, mobilier (importation, distribution)' },
    { title: 'Papeterie et fournitures de bureau' },
    { title: 'Photocopieurs, Reprographie' },
    { title: 'Pneus - Pneumatiques' },
    { title: 'Produits alimentaires (négoce, distribution)' },
    { title: 'Sports et loisirs (articles et équipements)' },
    { title: 'Supermarchés' },
    { title: 'Aciérie, Métallurgie' },
    { title: 'Allumettes de sûreté (Fabrication)' },
    { title: 'Bois (exploitation forestière)' },
    { title: 'Bois (negoce et exportation)' },
    { title: 'Bois (placage)' },
    { title: 'Bois (produits pour traitement)' },
    { title: 'Bois (scierie, séchage, transformation)' },
    { title: 'Broderie, marquage à façon' },
    { title: 'Confection textile' },
    { title: 'Filature' },
    { title: 'Gaz industriels et médicaux' },
    { title: 'Matelas mousse (fabrication, vente)' },
    { title: 'Peinture (fabrication)' },
    { title: 'Plastique (transformation)' },
    { title: 'Produits chimiques (négoce)' },
    { title: 'Produits phytosanitaires' },
    { title: 'Tôles ondulées métal (fabrication)' },
    { title: 'Traitement des eaux (produits) Vêtements, prêt à porter' },
    { title: 'Antennes paraboliques' },
    { title: 'Cybercafés' },
    { title: 'Informatique (matériel et fournitures)' },
    { title: 'Informatique (réseaux, câblage)' },
    { title: 'Informatique (services, conseil, formation)' },
    { title: 'Internet (création de sites)' },
    { title: 'Internet (FAI)' },
    { title: 'Télécommunications (systèmes intégrés)' },
    { title: 'Télédiffusion' },
    { title: 'Téléphonie (produits, consomables)' },
    { title: 'Téléphonie cellulaire (opérateur)' },
    { title: 'Télévision par satellilte (distributeurs)' },
    { title: 'Aluminium' },
    { title: 'Carburant' },
    { title: 'Eau (production, distribution)' },
    { title: 'Energie électrique (production, distribution)' },
    { title: 'Energie solaire' },
    { title: 'Energies renouvelables' },
    { title: 'Gaz (Recherche et production)' },
    { title: 'Mines, exploitation minières' },
    { title: 'Pétrole (inspection contrôle)' },
    { title: 'Pétrole (maintenance et assistance technique)' },
    { title: 'Pétrole (mise a disposition de personnel)' },
    { title: 'Pétrole (Raffinerie)' },
    { title: 'Pétrole (Recherche, Production)' },
    { title: 'Pétrole (sous traitant)' },
    { title: 'Produits pétroliers (distribution)' },
    { title: 'Produits pétroliers (entreposage) Station Service' },
    { title: 'Accueil aéroport, assistance, formalités' },
    { title: 'Affacturage, Recouvrement' },
    { title: 'Agences Conseil en communication' },
    { title: 'Agences immobilières' },
    { title: 'Archivage et tiers archivage' },
    { title: 'Armes, Cartouches, Explosifs' },
    { title: 'Audio-visuel (production)' },
    { title: 'Audit, Commissariat aux comptes' },
    { title: 'Avocats' },
    { title: 'Bureau de contrôle, Expertise' },
    { title: "Bureaux d'etudes" },
    { title: 'Certification, normalisation' },
    { title: 'Comptables - Comptabilité' },
    { title: 'Conseil en organisation' },
    { title: 'Conseil juridique et fiscal' },
    { title: 'Contrôle, suivi de travaux' },
    { title: "Création d'entreprise, domiciliation" },
    { title: 'Ecoles de langues' },
    { title: 'Editions - Publications' },
    { title: 'Emballages, cartonnage (fabrication)' },
    { title: 'Emploi (recherche et offre)' },
    { title: 'Enseignement (fondation, formation)' },
    { title: 'Etablissements scolaires (écoles, collèges, etc.)' },
    { title: 'Evénementiel' },
    { title: 'Expertise Comptable' },
    { title: 'Formation Professionnelle' },
    { title: 'Formation, Coaching' },
    { title: 'Gardiennage' },
    { title: 'Gestion externalisé de personnel' },
    { title: 'GRH, Recrutement' },
    { title: 'Huissiers de Justice' },
    { title: 'Impression numérique' },
    { title: 'Imprimeries' },
    { title: 'Ingénierie - Engineering' },
    { title: 'Instituts de recherche' },
    { title: 'Intérim' },
    { title: 'Librairies, Papeterie, Presse' },
    { title: 'Management, Marketing' },
    { title: 'Objets publicitaires' },
    { title: 'Photo, vidéo (studio, labo)' },
    { title: 'Promotion Immobiliere' },
    { title: 'Propriété industrielle' },
    { title: 'Publicité' },
    { title: 'Sécurité (entreprises)' },
    { title: 'Sérigraphie' },
    { title: 'Syndicats, Associations' },
    { title: 'Télésurveillance' },
    { title: 'Traitement des eaux (ingénierie), Zones Franches' },
    { title: 'Acconage' },
    { title: 'Affrètements maritimes' },
    { title: 'Compagnies aériennes' },
    { title: 'Consignation maritime' },
    { title: 'Construction navale' },
    { title: 'Courrier express, coursiers' },
    { title: 'Déménagement' },
    { title: 'Evacuations sanitaires' },
    { title: 'Expertise maritime' },
    { title: 'Fret maritime' },
    { title: 'Location de bateaux' },
    { title: "Location et affrètement d'avions" },
    { title: 'Manutention portuaire' },
    { title: 'Messagerie, routage' },
    { title: 'Moteurs (marins et hors-bord)' },
    { title: 'Ports (exploitation, gestion)' },
    { title: 'Sécurité aérienne' },
    { title: 'Transitaires' },
    { title: 'Transport de personnel' },
    { title: 'Transport ferroviaire' },
    { title: 'Transport maritime' },
    { title: 'Transport maritime (régulation, réglementation)' },
    { title: 'Transport routier' },
    { title: 'Cabinet Dentaire' },
    { title: 'Cabinet médical' },
    { title: 'Gynécologie obstétrique' },
    { title: 'Hôpital, Clinique, Polyclinique' },
    { title: "Laboratoire d'analyse médicale" },
    { title: 'Matériel médical et consommables' },
    { title: 'Optique' },
    { title: 'Produits pharmaceutiques (distribution)' },
    { title: 'Produits pharmaceutiques (fabrication)' },
    { title: 'Santé publique (organismes, fondations)' },
    { title: 'Administrations' },
    { title: 'Ambassades - Consulats' },
    { title: 'Institutions' },
    { title: 'Ministères' },
    { title: 'Organismes Publics et Parapublics' },
    { title: 'Assurances (compagnie)' },
    { title: 'Assurances (courtier)' },
    { title: 'Banques' },
    { title: 'Bourse (sociétés et organismes)' },
    { title: 'Bureau de Change' },
    { title: 'Crédit (organismes financiers)' },
    { title: 'Crédit-bail, Leasing' },
    { title: 'Etablissements de crédit à la consommation' },
    { title: 'Financement' },
    { title: 'Microfinance' },
    { title: "Transfert d'argent" },
    { title: 'Agences de voyages' },
    { title: 'Billeterie' },
    { title: 'Casinos et jeux' },
    { title: 'Coiffeurs' },
    { title: 'Esthétique, instituts de beauté' },
    { title: 'Hôtels' },
    { title: "Parcs d'attractions, de loisirs" },
    { title: 'Restaurants' },
    { title: 'Salons de Thé, Glaciers' },
    { title: 'Tourisme (organisation de circuits)' },
];
